alias sshc='ssh-cosmos'
alias bbcr='bbc-repo'
alias or='orbit-redis'
alias r='reith'
alias ro='reith on'
alias roff='reith off'
alias mpm='npm --registry https://npm.morph.int.tools.bbc.co.uk --cert="$(cat /etc/pki/tls/certs/client.crt)" --key="$(cat /etc/pki/tls/private/client.key)" --cafile=/etc/pki/tls/certs/ca-bundle.crt'
