alias aps='aws_cli_profile_set'
alias aswp='aws-switch-profile-fzf'
alias ecl='ecr-login'
alias ecls='ecr-login --switch'
alias awsdlg='aws logs describe-log-groups | jq --raw-output ".logGroups[].logGroupName"'
alias awsdls='aws logs describe-log-streams --log-group-name'
