(add-to-list 'load-path "~/.emacs.d/config")
(add-to-list 'load-path "~/.emacs.d/vendored")

(require 'straight)
(require 'hooks)
(require 'settings)
(require 'packages)
(require 'visual)
(require 'ligatures)
(require 'maps)
(require 'mac)
(require 'directories)
