(add-to-list 'load-path "~/.emacs.d/config")
(add-to-list 'load-path "~/.emacs.d/vendored")

(require 'packages)
(require 'jenkinsfile-mode)
(require 'paths)
(require 'initial-frame)
(require 'settings)
(require 'maps)
(require 'mac)
(require 'hooks)
