source $SCRIPTS/parse-args.sh
source $SCRIPTS/symlink-dotfiles.sh
source $SCRIPTS/copy-fonts.sh
source $SCRIPTS/install-brew-dependencies.sh
source $SCRIPTS/install-debian-deps.sh
source $SCRIPTS/install-linux-deps.sh
source $SCRIPTS/install-freebsd-deps.sh
source $SCRIPTS/set-macos-defaults.sh
source $SCRIPTS/install-python-3.sh
source $SCRIPTS/set-iterm-preferences-location.sh
source $SCRIPTS/install-npm-globals.sh
source $SCRIPTS/generate-ssh.sh
