require("disable-builtins")
require("bootstrap-packer")
require("bootstrap-packer")
require("plugins")
require("core-settings")
require("keys")
require("load-vim-config")
-- require("lsp.init")
require("custom-highlights")

