endpoint: https://jira.dev.bbc.co.uk
unixproxy: /usr/local/var/client-cert-proxy.sock
user: ben.wainwright@bbc.co.uk
project: WEBCOREDEVX
custom-commands:
  - name: current
    short: c
    help: Search JIRA for a given string
    script: |
      {{ jira }} list -t current --query "project = \"WEBCOREDEVX\" AND (status = \"Next\" OR status = \"In Progress\"  OR status = \"On-Hold\")"
