local vim = require("nvim-api")

vim.exec("let mapleader = \"\\<Space>\"")
vim.exec("let maplocalleader = \"\\\\\"")
vim.map("n", "<C-e>", "<cmd>NvimTreeToggle<CR>")
vim.map("n", "<leader>G", "<cmd>Ag<CR>")
vim.map("n", "<C-b>", "<cmd>Buffers<CR>")
vim.map("n", "<leader>cp", "<cmd>vs ~/.config/nvim/lua/plugins.lua<CR>")
vim.map("n", "<leader>cm", "<cmd>vs ~/.config/nvim/lua/keys.lua<CR>")
vim.map("n", "<leader>cl", "<cmd>vs ~/.config/nvim/lua/lsp.lua<CR>")
